#
#   ${project.name} v${project.version} by RezzedUp
#
#   ---
#
#   This plugin *requires* DiscordSRV.
#   (It won't load without it)
#   
#   ---
#
#   Installation:
#   - Install this plugin and DiscordSRV
#   - Add a 'staff-chat' channel to DiscordSRV's config
#     Example:
#         # Channel links from game to Discord
#         # Replace '00000000000' with your channel's id
#         Channels: {"global": "00000000000", "staff-chat": "00000000000"}
#         #                                        ^              ^
#         #                         All staff chat messages will be sent to this channel.
#     Note:
#     The channel's name can be anything on discord (since DiscordSRV uses its channel id), but
#     it MUST be called 'staff-chat' in the config.
#   - Restart the server
#   - Give staff ranks permission to use the staff chat: 'staffchat.access'
#
#   ---
#
#   This config can be reloaded in-game with: '/managestaffchat reload'
#

in-game-message-format: "&d(&5&l&oStaff&d) %name%&7:&f %message%"
discord-message-format: "&9&ldiscord &f&m-&f>&r &d(&5&l&oStaff&d) %name%&7:&f %message%"

#
#   Automatic staff-chat toggle messages.
#

enable-staff-chat: "&d(&5&l&oStaff&d) &a&m-&a> Enabled &fautomatic staff chat"
disable-staff-chat: "&d(&5&l&oStaff&d) &c&m-&c> Disabled &fautomatic staff chat"

#
#   If a staff member leaves the server with automatic staff chat enabled,
#   this plugin will remember and remind them upon joining back.
#   All toggles will be disabled if this plugin is unloaded (e.g. if the server restarts).
#

notify-staff-chat-enabled-on-join: true
staff-chat-enabled-notification: "&d(&5&l&oStaff&d) &a&m-&a> &fAutomatic staff chat is &aenabled"
