name: ${project.name}
version: ${project.version}
author: RezzedUp

main: ${project.groupId}.discordsrv.staffchat.StaffChatPlugin
softdepend: [DiscordSRV]

commands:
  staffchat:
    description: Toggle or send a message to staff chat.
    usage: |-
      /<command> - toggle automatic staff chat
      /<command> <message> - send a message to the staff chat
    permission: staffchat.access
    aliases: [adminchat, schat, achat, sc, ac, a]
  managestaffchat:
    description: Manage and get information about DiscordSRV-Staff-Chat
    usage: /<command>
    permission: staffchat.manage
    aliases: [discordstaffchat, discordadminchat, manageadminchat, managesc, manageac, dsc, msc, dac, mac]

permissions:
  staffchat.*:
    children:
      staffchat.manage: true
      staffchat.access: true
  staffchat.manage:
    description: Allows players to manage the plugin in-game (e.g. reloading)
  staffchat.access:
    descriptions: Allows players to access the staff chat.
